plugins {
    id 'java'
}

group = "at.helpch.papi.expansion.hyvotifier"
version = '1.0.0'
description = "HyVotifier Expansion for PlaceholderAPI"

repositories {
    mavenCentral()
    mavenLocal()

    maven { url "https://maven.hytale.com/release/" }
    maven { url "https://repo.helpch.at/releases" }
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withSourcesJar()
}

dependencies {
    compileOnly "com.hypixel.hytale:Server:2026.01.24-6e2d4fc36"
    compileOnly "at.helpch:placeholderapi-hytale:1.0.3"
    compileOnly files('libs/hytale-votifier-2.2.0.jar')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('jar') {
    archiveBaseName.set('PAPI-Expansion-HyVotifier')
    manifest {
        attributes(
            'Implementation-Title': project.name,
            'Implementation-Version': project.version
        )
    }
}
